AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AlarmName:
    Description: create alarm
    Type: String
  OperatorEmail:
    Description: Email address to notify if there are any scaling operations
    Type: String
Resources:
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if CPUUtilization > 20"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
      - Name: InstanceId
        Value: i-080ced40c0ad5c08f
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '20'
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref 'AlarmNotificationTopic']
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref 'OperatorEmail'
        Protocol: email
